server.port=9090
spring.application.name=customers-prod
app.log-message=Ejecutando en PROD

spring.datasource.url=jdbc:postgresql://db:5433/customersdb
spring.datasource.username=admin
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false