server.port=9090
spring.application.name=customers-prod
app.log-message=Ejecutando en PROD

spring.datasource.url=jdbc:postgresql://db:5432/customersdb_prod
spring.datasource.username=admin
spring.datasource.password=${POSTGRES_PASSWORD:clave}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false